blueprint:
  name: Motion Lighting by House Mode
  description: >-
    Motion-activated lighting that adapts brightness based on a global house mode (Day, Evening, Night),
    with optional enable/disable toggle, per-mode disable, auto-off timer, and optional auto re-enable.
    House mode is optional — leave blank for simple full-brightness motion lighting.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    lights:
      name: Lights
      selector:
        target:
          entity: 
            domain: light
    house_mode:
      name: House Mode Selector (Optional)
      description: >-
        Optional input_select with options Day/Evening/Night. Leave blank for fixed brightness.
      default: ""
      selector:
        entity:
          domain: input_select
    motion_enabled:
      name: Motion Lighting Enabled Toggle (Optional)
      description: >-
        Optional. If not set, motion lighting is always enabled.
      default: ""
      selector:
        entity:
          domain: input_boolean
    disable_in_modes:
      name: Disable Motion In These Modes
      description: House modes where motion should NOT turn lights on (only used if house mode selected)
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night
    day_brightness:
      name: Day / Default Brightness %
      description: Used for Day mode or when no house mode is selected
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    no_motion_off_delay:
      name: Minutes to Turn Lights Off After No Motion
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    auto_reenable_delay:
      name: Minutes to Auto Re-Enable Motion Lighting
      description: >-
        Only used if a Motion Lighting Enabled Toggle is selected.
      default: 30
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      minutes: !input no_motion_off_delay

variables:
  house_mode_entity: !input house_mode
  motion_enabled_entity: !input motion_enabled
  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else '' }}"
  disabled_modes: !input disable_in_modes

action:
  - choose:
      # TURN LIGHTS ON
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
          - condition: template
            value_template: >-
              {{ motion_enabled_entity == '' or is_state(motion_enabled_entity, 'on') }}
          - condition: template
            value_template: >-
              {{ current_mode not in disabled_modes }}
        sequence:
          - choose:
              - conditions: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: !input day_brightness
              - conditions: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: !input evening_brightness
              - conditions: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: !input night_brightness
            default:
              - service: light.turn_on
                target: !input lights
                data:
                  brightness_pct: !input day_brightness

      # TURN LIGHTS OFF + OPTIONAL AUTO RE-ENABLE
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - service: light.turn_off
            target: !input lights
          - if:
              - condition: template
                value_template: "{{ motion_enabled_entity != '' }}"
            then:
              - delay:
                  minutes: !input auto_reenable_delay
              - if:
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "off"
                then:
                  - service: input_boolean.turn_on
                    data_template:
                      entity_id: "{{ motion_enabled_entity }}"
