blueprint:
  name: Motion Lighting by House Mode (Area + Night Fan Hold) v1.3
  description: >
    Motion-based lighting using a single Area.
    Lights always auto-off after no motion.
    Fans turn off after no motion EXCEPT in Night mode (stay on all night).
  domain: automation

  input:
    main_area:
      name: Main Room / Area
      selector:
        area:

    house_mode:
      name: House Mode Selector
      selector:
        entity:
          domain: input_select

    disable_auto_on:
      name: Disable Auto Turn-On Toggle
      default: ""
      selector:
        entity:
          domain: input_boolean

    disable_in_modes:
      name: Disable Motion Turn-On In These Modes
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100

    no_motion_off_delay:
      name: Minutes After No Motion to Turn Off
      default: 5
      selector:
        number:
          min: 1
          max: 60

mode: restart

variables:
  area_id: !input main_area
  house_mode_entity: !input house_mode
  disabled_modes: !input disable_in_modes
  disable_auto_on_entity: !input disable_auto_on

  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else 'Day' }}"
  keep_fan_on: "{{ current_mode == 'Night' }}"

  motion_entities: "{{ area_entities(area_id) | select('match', '^binary_sensor\\..*(motion|occupancy)$') | list }}"
  light_entities: "{{ area_entities(area_id) | select('match', '^light\\.') | list }}"
  fan_entities: "{{ area_entities(area_id) | select('match', '^(fan|switch)\\.') | list }}"

trigger:
  - platform: state
    entity_id: "{{ motion_entities }}"
    to: "on"

  - platform: state
    entity_id: "{{ motion_entities }}"
    to: "off"
    for:
      minutes: !input no_motion_off_delay

action:
  - choose:

      # -------------------------
      # MOTION ON → TURN LIGHTS ON
      # -------------------------
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
          - condition: template
            value_template: "{{ current_mode not in disabled_modes }}"
          - condition: template
            value_template: "{{ disable_auto_on_entity == '' or is_state(disable_auto_on_entity, 'off') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input day_brightness

              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input evening_brightness

              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input night_brightness

      # ---------------------------------
      # NO MOTION → TURN LIGHTS OFF
      # ---------------------------------
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_entities }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not keep_fan_on }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: "{{ fan_entities }}"
