blueprint:
  name: Motion Lighting by House Mode
  description: >
    Turn lights on via motion based on house mode (Day/Evening/Night),
    with brightness control, per-mode disable, auto-off timer,
    and automatic re-enable of motion lighting after no motion.
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    lights:
      name: Lights
      selector:
        target:
          entity:
            domain: light

    house_mode:
      name: House Mode Selector
      selector:
        entity:
          domain: input_select

    motion_enabled:
      name: Motion Lighting Enabled Toggle
      selector:
        entity:
          domain: input_boolean

    disable_in_modes:
      name: Disable Motion In These Modes
      description: Select house modes where motion should NOT turn lights on
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    no_motion_off_delay:
      name: Minutes to Turn Lights Off After No Motion
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

    auto_reenable_delay:
      name: Minutes to Auto Re-Enable Motion Lighting
      default: 30
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      minutes: !input no_motion_off_delay

variables:
  current_mode: "{{ states(!input house_mode) }}"

action:
  - choose:

      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "on"

          - condition: state
            entity_id: !input motion_enabled
            state: "on"

          - condition: template
            value_template: >
              {{ current_mode not in !input disable_in_modes }}

        sequence:
          - choose:
              - conditions: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: 100

              - conditions: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: !input evening_brightness

              - conditions: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
                    data:
                      brightness_pct: !input night_brightness

      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - service: light.turn_off
            target: !input lights

          - delay:
              minutes: !input auto_reenable_delay

          - condition: state
            entity_id: !input motion_sensor
            state: "off"

          - service: input_boolean.turn_on
            target:
              entity_id: !input motion_enabled
