# Motion-controlled lights or switches blueprint
# Version: 1.1.0

blueprint:
  name: Motion-controlled light or switch (on/off with delay) v1.1.0
  description: >
    Version: 1.1.0
    Turns a light or switch on when motion or occupancy is detected
    and turns it off after no motion is detected for a configurable time.
  domain: automation

  input:
    motion_sensors:
      name: Motion / Occupancy sensor(s)
      description: One or more motion or occupancy binary sensors
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    target_entities:
      name: Light(s) or Switch(es)
      description: Light(s) or switch(es) to control
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    off_delay:
      name: Delay before turning off
      description: Time to wait after motion stops
      default: 5
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

  - platform: state
    entity_id: !input motion_sensors
    to: "off"

action:
  - choose:
      # Motion detected → turn on
      - conditions:
          - condition: state
            entity_id: !input motion_sensors
            state: "on"
        sequence:
          - service: homeassistant.turn_on
            target: !input target_entities

      # No motion → wait, then turn off
      - conditions:
          - condition: state
            entity_id: !input motion_sensors
            state: "off"
        sequence:
          - delay:
              minutes: !input off_delay
          - condition: state
            entity_id: !input motion_sensors
            state: "off"
          - service: homeassistant.turn_off
            target: !input target_entities
