blueprint:
  name: Motion Lighting by House Mode (Single Area + Fan Stays On at Night)
  description: >-
    Single-area motion lighting. Lights always auto-off.
    Fans auto-off only in Day/Evening — stay on all night in Night mode.
  domain: automation

  input:
    main_area:
      name: Main Room/Area
      description: Primary area — auto-detects motion sensors, lights, and fans
      selector:
        area:

    exclude_label:
      name: Exclude Lights with This Label (Optional)
      default: ""
      selector:
        text:

    # --- Advanced Overrides ---
    use_override_sensors:
      name: Override Motion Sensors? (Advanced)
      default: false
      selector:
        boolean:

    override_motion_sensors:
      name: Custom Motion/Occupancy Sensors
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true
      default: []

    use_override_lights:
      name: Override Lights? (Advanced)
      default: false
      selector:
        boolean:

    override_lights:
      name: Custom Lights
      selector:
        target:
          entity:
            domain: light
      default: []

    use_override_fans:
      name: Override Fans/Exhaust? (Advanced)
      default: false
      selector:
        boolean:

    override_fan_entities:
      name: Custom Fans/Exhaust
      selector:
        target:
          entity:
            domain:
              - fan
              - switch
      default: []

    disable_auto_on:
      name: Disable Auto Turn-On Toggle (Optional)
      description: >-
        When ON: Motion will NOT turn lights on (manual only). Add to dashboard.
      default: ""
      selector:
        entity:
          domain: input_boolean

    house_mode:
      name: House Mode Selector (Required for Night Fan Behavior)
      description: input_select with Day/Evening/Night options
      selector:
        entity:
          domain: input_select

    disable_in_modes:
      name: Disable Motion In These Modes
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day / Default Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    enable_ramping:
      name: Enable Brightness Ramping
      default: false
      selector:
        boolean:

    ramp_time:
      name: Ramp Time (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds

    no_motion_off_delay:
      name: Minutes to Wait After No Motion
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart

variables:
  area_id: !input main_area
  house_mode_entity: !input house_mode
  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else 'Day' }}"
  disabled_modes: !input disable_in_modes
  ramp_enabled: !input enable_ramping
  ramp_seconds: "{{ !input ramp_time if ramp_enabled else 0 }}"

  motion_entities: >
    {% if !input use_override_sensors %}
      {{ area_entities(area_id) | select('match', '^binary_sensor\\..*(motion|occupancy)$') | list }}
    {% else %}
      {{ !input override_motion_sensors }}
    {% endif %}

  light_entities: >
    {% if !input use_override_lights %}
      {% set all_lights = area_entities(area_id) | select('match', '^light\\.') | list %}
      {% if !input exclude_label != '' %}
        {% set excluded = expand(label_entities(!input exclude_label)) | selectattr('domain', 'eq', 'light') | map(attribute='entity_id') | list %}
        {{ all_lights | reject('in', excluded) | list }}
      {% else %}
        {{ all_lights }}
      {% endif %}
    {% else %}
      {{ (!input override_lights).entity_id | default([]) }}
    {% endif %}

  fan_entities: >
    {% if !input use_override_fans %}
      {{ area_entities(area_id) | select('match', '^(fan|switch)\\.') | list }}
    {% else %}
      {{ (!input override_fan_entities).entity_id | default([]) }}
    {% endif %}

  # True if we should skip turning off fans (i.e., it's Night mode)
  keep_fan_on: "{{ current_mode == 'Night' }}"

action:
  - choose:

      # TURN LIGHTS ON (if allowed)
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "on"
          - condition: template
            value_template: "{{ current_mode not in disabled_modes }}"
          - condition: template
            value_template: "{{ !input disable_auto_on == '' or is_state(!input disable_auto_on, 'off') }}"
          - condition: template
            value_template: "{{ light_entities | length > 0 }}"
        sequence:
          - choose:
              - conditions: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input day_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input evening_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input night_brightness
                      transition: "{{ ramp_seconds }}"

            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  brightness_pct: !input day_brightness
                  transition: "{{ ramp_seconds }}"

      # TURN OFF LIGHTS + FANS (conditionally for fans)
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "off"

        sequence:
          # Always turn off lights
          - if: "{{ light_entities | length > 0 }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  transition: "{{ ramp_seconds }}"

          # Turn off fans only if NOT in Night mode
          - if: "{{ fan_entities | length > 0 and not keep_fan_on }}"
            then:
              - service: homeassistant.turn_off
                target:
                  entity_id: "{{ fan_entities }}"
