blueprint:
  name: Motion Lighting by House Mode (Area + Night Fan Hold) v1.50
  description: >
    Full-feature motion lighting blueprint for a single area.

    Features:
    - Auto-discover motion sensors, lights, fans/switches by Area
    - Optional overrides for sensors/lights/fans
    - Optional exclude-by-label for lights
    - House mode (Day/Evening/Night) controls brightness and night fan behavior
    - Optional disable-auto-on toggle (still allows auto-off)
    - Smooth ramping option with ramp duration
    - Lights ALWAYS turn off after no motion delay (even if manually turned on)
    - Fans turn off after no motion EXCEPT Night mode (stay on all night)
  domain: automation

  input:
    main_area:
      name: Main Room / Area
      selector:
        area:

    exclude_label:
      name: Exclude Lights with This Label (Optional)
      default: ""
      selector:
        text:

    use_override_sensors:
      name: Override Motion Sensors? (Advanced)
      default: false
      selector:
        boolean:

    override_motion_sensors:
      name: Custom Motion/Occupancy Sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true

    use_override_lights:
      name: Override Lights? (Advanced)
      default: false
      selector:
        boolean:

    override_lights:
      name: Custom Lights
      default: {}
      selector:
        target:
          entity:
            domain: light

    use_override_fans:
      name: Override Fans/Exhaust? (Advanced)
      default: false
      selector:
        boolean:

    override_fan_entities:
      name: Custom Fan / Switch Entities
      default: {}
      selector:
        target:
          entity:
            domain:
              - fan
              - switch

    disable_auto_on:
      name: Disable Auto Turn-On Toggle (Optional)
      default: ""
      selector:
        entity:
          domain: input_boolean

    house_mode:
      name: House Mode Selector (Recommended)
      selector:
        entity:
          domain: input_select

    disable_in_modes:
      name: Disable Motion Turn-On In These Modes (Optional)
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    enable_ramping:
      name: Enable Smooth Ramping (Fade On/Off)
      default: false
      selector:
        boolean:

    ramp_time:
      name: Ramp/Fade Time (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds

    no_motion_off_delay:
      name: Minutes to Wait After No Motion Before Turning Off
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart

variables:
  area_id: !input main_area

  house_mode_entity: !input house_mode
  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else 'Day' }}"

  disabled_modes: !input disable_in_modes

  disable_auto_on_entity: !input disable_auto_on

  enable_ramping_val: !input enable_ramping
  ramp_time_val: !input ramp_time

  use_override_sensors_val: !input use_override_sensors
  use_override_lights_val: !input use_override_lights
  use_override_fans_val: !input use_override_fans

  override_motion_sensors_val: !input override_motion_sensors
  override_lights_val: !input override_lights
  override_fan_entities_val: !input override_fan_entities

  exclude_label_val: !input exclude_label

  # Entity resolution
  motion_entities: >-
    {% if use_override_sensors_val %}
      {{ override_motion_sensors_val }}
    {% else %}
      {{ area_entities(area_id)
         | select('match', '^binary_sensor\\..*(motion|occupancy)$')
         | list }}
    {% endif %}

  light_entities: >-
    {% if use_override_lights_val %}
      {{ override_lights_val.entity_id | default([]) }}
    {% else %}
      {% set all_lights = area_entities(area_id)
           | select('match', '^light\\.')
           | list %}
      {% if exclude_label_val != '' %}
        {% set excluded = expand(label_entities(exclude_label_val))
             | selectattr('domain', 'eq', 'light')
             | map(attribute='entity_id')
             | list %}
        {{ all_lights | reject('in', excluded) | list }}
      {% else %}
        {{ all_lights }}
      {% endif %}
    {% endif %}

  fan_entities: >-
    {% if use_override_fans_val %}
      {{ override_fan_entities_val.entity_id | default([]) }}
    {% else %}
      {{ area_entities(area_id)
         | select('match', '^(fan|switch)\\.')
         | list }}
    {% endif %}

  keep_fan_on: "{{ current_mode == 'Night' }}"

  # Template-friendly occupancy checks
  any_motion_on: "{{ expand(motion_entities) | selectattr('state','eq','on') | list | count > 0 }}"
  all_motion_off: "{{ expand(motion_entities) | selectattr('state','eq','on') | list | count == 0 }}"

trigger:
  # IMPORTANT: template triggers avoid templated entity_id (which HA rejects)
  - platform: template
    id: motion_on
    value_template: "{{ any_motion_on }}"

  - platform: template
    id: motion_off
    value_template: "{{ all_motion_off }}"
    for:
      minutes: !input no_motion_off_delay

action:
  - choose:

      # -------------------------
      # MOTION ON -> LIGHTS ON
      # -------------------------
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: template
            value_template: "{{ current_mode not in disabled_modes }}"
          - condition: template
            value_template: "{{ disable_auto_on_entity == '' or is_state(disable_auto_on_entity, 'off') }}"
          - condition: template
            value_template: "{{ light_entities | length > 0 }}"
        sequence:

          # RAMPING ON
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_ramping_val }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ current_mode == 'Day' }}"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: "{{ light_entities }}"
                            data:
                              brightness_pct: !input day_brightness
                              transition: !input ramp_time

                      - conditions:
                          - condition: template
                            value_template: "{{ current_mode == 'Evening' }}"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: "{{ light_entities }}"
                            data:
                              brightness_pct: !input evening_brightness
                              transition: !input ramp_time

                      - conditions:
                          - condition: template
                            value_template: "{{ current_mode == 'Night' }}"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: "{{ light_entities }}"
                            data:
                              brightness_pct: !input night_brightness
                              transition: !input ramp_time

            # RAMPING OFF (no transition key)
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ current_mode == 'Day' }}"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ light_entities }}"
                        data:
                          brightness_pct: !input day_brightness

                  - conditions:
                      - condition: template
                        value_template: "{{ current_mode == 'Evening' }}"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ light_entities }}"
                        data:
                          brightness_pct: !input evening_brightness

                  - conditions:
                      - condition: template
                        value_template: "{{ current_mode == 'Night' }}"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ light_entities }}"
                        data:
                          brightness_pct: !input night_brightness

      # -------------------------
      # NO MOTION -> LIGHTS OFF (+ FANS OFF unless Night)
      # -------------------------
      - conditions:
          - condition: trigger
            id: motion_off
        sequence:

          # Lights off (with ramp if enabled)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ enable_ramping_val }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      transition: !input ramp_time
            default:
              - service: light.turn_off
                target:
                  entity_id: "{{ light_entities }}"

          # Fans off only if NOT Night mode
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ fan_entities | length > 0 and not keep_fan_on }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: "{{ fan_entities }}"
