blueprint:
  name: Motion Lighting by House Mode (Single Area + Optional Overrides)
  description: >-
    Simple setup: Select one area and it auto-detects motion sensors, lights, and fans.
    Optional overrides for advanced control. Lights always auto-off.
  domain: automation

  input:
    main_area:
      name: Main Room/Area
      description: The primary area — motion sensors, lights, and fans will be auto-detected from here
      selector:
        area:

    exclude_label:
      name: Exclude Lights with This Label (Optional)
      description: Lights in the area with this label will not be controlled
      default: ""
      selector:
        text:

    # --- Advanced Overrides (Optional) ---
    use_override_sensors:
      name: Override Motion Sensors? (Advanced)
      description: Enable to manually select specific motion sensors instead of using all in area
      default: false
      selector:
        boolean:

    override_motion_sensors:
      name: Custom Motion/Occupancy Sensors
      description: Only used if override enabled above
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true
      default: []

    use_override_lights:
      name: Override Lights? (Advanced)
      description: Enable to manually select specific lights instead of all in area
      default: false
      selector:
        boolean:

    override_lights:
      name: Custom Lights
      description: Only used if override enabled above
      selector:
        target:
          entity:
            domain: light
      default: []

    use_override_fans:
      name: Override Fans/Exhaust? (Advanced)
      description: Enable to manually select specific fans/switches instead of all in area
      default: false
      selector:
        boolean:

    override_fan_entities:
      name: Custom Fans/Exhaust Entities
      description: Only used if override enabled above
      selector:
        target:
          entity:
            domain:
              - fan
              - switch
      default: []

    disable_auto_on:
      name: Disable Auto Turn-On Toggle (Optional)
      description: >-
        When ON: Motion will NOT turn lights on (manual only), but auto-off still works.
        Great for bathrooms. Add this input_boolean to your dashboard for easy control!
      default: ""
      selector:
        entity:
          domain: input_boolean

    house_mode:
      name: House Mode Selector (Optional)
      default: ""
      selector:
        entity:
          domain: input_select

    motion_enabled:
      name: Motion Lighting Enabled Toggle (Optional)
      default: ""
      selector:
        entity:
          domain: input_boolean

    disable_in_modes:
      name: Disable Motion In These Modes
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day / Default Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    enable_ramping:
      name: Enable Brightness Ramping
      default: false
      selector:
        boolean:

    ramp_time:
      name: Ramp Time (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds

    no_motion_off_delay:
      name: Minutes to Wait After No Motion
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

    auto_reenable_delay:
      name: Minutes to Auto Re-Enable Motion Lighting
      default: 30
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    to: "on"
    for: 1

  - platform: state
    to: "off"
    for:
      minutes: !input no_motion_off_delay

variables:
  area_id: !input main_area

  motion_entities: >
    {% if !input use_override_sensors %}
      {{ area_entities(area_id) | select('match', '^binary_sensor\\..*_(motion|occupancy)$') | list }}
    {% else %}
      {{ !input override_motion_sensors }}
    {% endif %}

  light_entities: >
    {% set all_lights = area_entities(area_id) | select('match', '^light\\.') | list %}
    {% if !input use_override_lights %}
      {% if !input exclude_label != '' %}
        {% set excluded = expand(label_entities(!input exclude_label)) | map(attribute='entity_id') | list %}
        {{ all_lights | reject('in', excluded) | list }}
      {% else %}
        {{ all_lights }}
      {% endif %}
    {% else %}
      {{ (!input override_lights).entity_id | default([]) }}
    {% endif %}

  fan_entities: >
    {% if !input use_override_fans %}
      {{ area_entities(area_id) | select('match', '^(fan|switch)\\.') | list }}
    {% else %}
      {{ (!input override_fan_entities).entity_id | default([]) }}
    {% endif %}

  current_mode: "{{ states(!input house_mode) if !input house_mode != '' else '' }}"
  ramp_seconds: "{{ !input ramp_time if !input enable_ramping else 0 }}"

action:
  - choose:
      # Motion On → Turn Lights On (if allowed)
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "on"
          - condition: template
            value_template: "{{ !input motion_enabled == '' or is_state(!input motion_enabled, 'on') }}"
          - condition: template
            value_template: "{{ current_mode not in !input disable_in_modes }}"
          - condition: template
            value_template: "{{ !input disable_auto_on == '' or is_state(!input disable_auto_on, 'off') }}"
          - condition: template
            value_template: "{{ light_entities | length > 0 }}"
        sequence:
          - choose:
              - conditions: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input day_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input evening_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input night_brightness
                      transition: "{{ ramp_seconds }}"

            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  brightness_pct: !input day_brightness
                  transition: "{{ ramp_seconds }}"

      # No Motion → Turn Off Lights + Fans
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "off"
          - condition: template
            value_template: "{{ !input motion_enabled == '' or is_state(!input motion_enabled, 'on') }}"
        sequence:
          - if: "{{ light_entities | length > 0 }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  transition: "{{ ramp_seconds }}"

          - if: "{{ fan_entities | length > 0 }}"
            then:
              - service: homeassistant.turn_off
                target:
                  entity_id: "{{ fan_entities }}"

          # Auto re-enable global toggle
          - if: "{{ !input motion_enabled != '' }}"
            then:
              - delay:
                  minutes: !input auto_reenable_delay
              - if:
                  - condition: state
                    entity_id: "{{ motion_entities }}"
                    state: "off"
                then:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: !input motion_enabled
