blueprint:
  name: Motion Lighting by House Mode (Area + Night Fan Hold) v1.4
  description: >
    Full-feature motion lighting blueprint.
    • Area-based auto discovery
    • Optional override sensors / lights / fans
    • Optional exclude-by-label for lights
    • Disable-auto-on toggle
    • House modes: Day / Evening / Night
    • Mode-based brightness
    • Lights always auto-off
    • Fans auto-off except Night mode (stay on all night)
  domain: automation

  input:
    main_area:
      name: Main Room / Area
      selector:
        area:

    exclude_label:
      name: Exclude Lights with This Label
      default: ""
      selector:
        text:

    use_override_sensors:
      name: Override Motion Sensors?
      default: false
      selector:
        boolean:

    override_motion_sensors:
      name: Custom Motion Sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true

    use_override_lights:
      name: Override Lights?
      default: false
      selector:
        boolean:

    override_lights:
      name: Custom Lights
      default: {}
      selector:
        target:
          entity:
            domain: light

    use_override_fans:
      name: Override Fans / Exhaust?
      default: false
      selector:
        boolean:

    override_fan_entities:
      name: Custom Fan / Switch Entities
      default: {}
      selector:
        target:
          entity:
            domain:
              - fan
              - switch

    disable_auto_on:
      name: Disable Auto Turn-On Toggle
      default: ""
      selector:
        entity:
          domain: input_boolean

    house_mode:
      name: House Mode Selector
      selector:
        entity:
          domain: input_select

    disable_in_modes:
      name: Disable Motion-On In These Modes
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100

    no_motion_off_delay:
      name: Minutes After No Motion to Turn Off
      default: 5
      selector:
        number:
          min: 1
          max: 60

mode: restart

variables:
  area_id: !input main_area

  house_mode_entity: !input house_mode
  disable_auto_on_entity: !input disable_auto_on
  disabled_modes: !input disable_in_modes
  exclude_label_val: !input exclude_label

  use_override_sensors_val: !input use_override_sensors
  use_override_lights_val: !input use_override_lights
  use_override_fans_val: !input use_override_fans

  override_motion_sensors_val: !input override_motion_sensors
  override_lights_val: !input override_lights
  override_fan_entities_val: !input override_fan_entities

  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else 'Day' }}"
  keep_fan_on: "{{ current_mode == 'Night' }}"

  motion_entities: >-
    {% if use_override_sensors_val %}
      {{ override_motion_sensors_val }}
    {% else %}
      {{ area_entities(area_id)
         | select('match', '^binary_sensor\\..*(motion|occupancy)$')
         | list }}
    {% endif %}

  light_entities: >-
    {% if use_override_lights_val %}
      {{ override_lights_val.entity_id | default([]) }}
    {% else %}
      {% set all_lights = area_entities(area_id)
           | select('match', '^light\\.')
           | list %}
      {% if exclude_label_val != '' %}
        {% set excluded = expand(label_entities(exclude_label_val))
             | selectattr('domain', 'eq', 'light')
             | map(attribute='entity_id')
             | list %}
        {{ all_lights | reject('in', excluded) | list }}
      {% else %}
        {{ all_lights }}
      {% endif %}
    {% endif %}

  fan_entities: >-
    {% if use_override_fans_val %}
      {{ override_fan_entities_val.entity_id | default([]) }}
    {% else %}
      {{ area_entities(area_id)
         | select('match', '^(fan|switch)\\.')
         | list }}
    {% endif %}

trigger:
  - platform: state
    entity_id: "{{ motion_entities }}"
    to: "on"

  - platform: state
    entity_id: "{{ motion_entities }}"
    to: "off"
    for:
      minutes: !input no_motion_off_delay

action:
  - choose:

      # MOTION ON → TURN LIGHTS ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
          - condition: template
            value_template: "{{ current_mode not in disabled_modes }}"
          - condition: template
            value_template: "{{ disable_auto_on_entity == '' or is_state(disable_auto_on_entity, 'off') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input day_brightness

              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input evening_brightness

              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input night_brightness

      # NO MOTION → TURN LIGHTS + FANS OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_entities }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not keep_fan_on }}"
                sequence:
                  - service: homeassistant.turn_off
                    target:
                      entity_id: "{{ fan_entities }}"
