blueprint:
  name: Motion Lighting by House Mode (Single Area + Optional Overrides)
  description: >-
    Simple: Select one area → auto-detects motion sensors, lights, fans.
    Lights/fans ALWAYS auto-off after no motion (even if manually turned on).
    Optional Disable Auto Turn-On toggle + advanced overrides.
  domain: automation

  input:
    main_area:
      name: Main Room/Area
      description: The primary area — motion sensors, lights, and fans auto-detected from here
      selector:
        area:

    exclude_label:
      name: Exclude Lights with This Label (Optional)
      description: Lights in the area with this label will NOT be controlled
      default: ""
      selector:
        text:

    # --- Advanced Overrides (Optional) ---
    use_override_sensors:
      name: Override Motion Sensors? (Advanced)
      description: Enable to manually select specific motion sensors instead of area auto-detect
      default: false
      selector:
        boolean:

    override_motion_sensors:
      name: Custom Motion/Occupancy Sensors
      description: Only used if override enabled above
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true
      default: []

    use_override_lights:
      name: Override Lights? (Advanced)
      description: Enable to manually select specific lights instead of area auto-detect
      default: false
      selector:
        boolean:

    override_lights:
      name: Custom Lights
      description: Only used if override enabled above
      selector:
        target:
          entity:
            domain: light
      default: []

    use_override_fans:
      name: Override Fans/Exhaust? (Advanced)
      description: Enable to manually select specific fans/switches
      default: false
      selector:
        boolean:

    override_fan_entities:
      name: Custom Fans/Exhaust
      description: Only used if override enabled above
      selector:
        target:
          entity:
            domain:
              - fan
              - switch
      default: []

    disable_auto_on:
      name: Disable Auto Turn-On Toggle (Optional)
      description: >-
        When ON: Motion will NOT turn lights on (manual on only), auto-off still works.
        Add to dashboard for per-room control (e.g., bathroom mode).
      default: ""
      selector:
        entity:
          domain: input_boolean

    house_mode:
      name: House Mode Selector (Optional)
      description: input_select with Day/Evening/Night options
      default: ""
      selector:
        entity:
          domain: input_select

    disable_in_modes:
      name: Disable Motion In These Modes
      description: House modes where motion should NOT turn lights on
      default: []
      selector:
        select:
          multiple: true
          options:
            - Day
            - Evening
            - Night

    day_brightness:
      name: Day / Default Brightness %
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    evening_brightness:
      name: Evening Brightness %
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness %
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    enable_ramping:
      name: Enable Brightness Ramping
      default: false
      selector:
        boolean:

    ramp_time:
      name: Ramp Time (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds

    no_motion_off_delay:
      name: Minutes to Wait After No Motion
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    entity_id:
      - "{{ area_entities(!input main_area) | select('match', '^binary_sensor\\.(?!.*(battery|wifi|link_quality|device_tracker|person|update|problem))') | select('match', 'motion|occupancy') | list }}"
    to: "on"

  - platform: state
    entity_id:
      - "{{ area_entities(!input main_area) | select('match', '^binary_sensor\\.(?!.*(battery|wifi|link_quality|device_tracker|person|update|problem))') | select('match', 'motion|occupancy') | list }}"
    to: "off"
    for:
      minutes: !input no_motion_off_delay

variables:
  area_id: !input main_area
  house_mode_entity: !input house_mode
  disable_auto_on_entity: !input disable_auto_on
  current_mode: "{{ states(house_mode_entity) if house_mode_entity != '' else '' }}"
  disabled_modes: !input disable_in_modes
  ramp_enabled: !input enable_ramping
  ramp_seconds: "{{ !input ramp_time if ramp_enabled else 0 }}"

  motion_entities: >
    {% if !input use_override_sensors %}
      {{ area_entities(area_id) | select('match', '^binary_sensor\\..*(motion|occupancy)$') | reject('match', '.*(battery|wifi|link_quality|device_tracker|person|update|problem).*') | list }}
    {% else %}
      {{ !input override_motion_sensors }}
    {% endif %}

  light_entities: >
    {% if !input use_override_lights %}
      {% set all_lights = area_entities(area_id) | select('match', '^light\\.') | list %}
      {% if !input exclude_label != '' %}
        {% set excluded = expand(label_entities(!input exclude_label)) | selectattr('domain', 'eq', 'light') | map(attribute='entity_id') | list %}
        {{ all_lights | reject('in', excluded) | list }}
      {% else %}
        {{ all_lights }}
      {% endif %}
    {% else %}
      {{ (!input override_lights).entity_id | default([]) }}
    {% endif %}

  fan_entities: >
    {% if !input use_override_fans %}
      {{ area_entities(area_id) | select('match', '^(fan|switch)\\.') | reject('match', '.*(battery|wifi|link_quality|device_tracker|person|update|problem).*') | list }}
    {% else %}
      {{ (!input override_fan_entities).entity_id | default([]) }}
    {% endif %}

action:
  - choose:

      # -------------------------
      # TURN LIGHTS ON (if auto-on allowed)
      # -------------------------
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "on"

          - condition: template
            value_template: >-
              {{ current_mode not in disabled_modes }}

          - condition: template
            value_template: >-
              {{ disable_auto_on_entity == '' or is_state(disable_auto_on_entity, 'off') }}

          - condition: template
            value_template: "{{ light_entities | length > 0 }}"

        sequence:
          - choose:

              - conditions: "{{ current_mode == 'Day' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input day_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Evening' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input evening_brightness
                      transition: "{{ ramp_seconds }}"

              - conditions: "{{ current_mode == 'Night' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light_entities }}"
                    data:
                      brightness_pct: !input night_brightness
                      transition: "{{ ramp_seconds }}"

            default:
              - service: light.turn_on
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  brightness_pct: !input day_brightness
                  transition: "{{ ramp_seconds }}"

      # -------------------------
      # TURN OFF LIGHTS + FANS (ALWAYS when room empty)
      # -------------------------
      - conditions:
          - condition: state
            entity_id: "{{ motion_entities }}"
            state: "off"

        sequence:
          # Turn off lights
          - if:
              - condition: template
                value_template: "{{ light_entities | length > 0 }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: "{{ light_entities }}"
                data:
                  transition: "{{ ramp_seconds }}"

          # Turn off fans/exhaust
          - if:
              - condition: template
                value_template: "{{ fan_entities | length > 0 }}"
            then:
              - service: homeassistant.turn_off
                target:
                  entity_id: "{{ fan_entities }}"
